plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.2'
    id 'io.spring.dependency-management' version '1.1.5'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    // MySQL
    runtimeOnly 'com.mysql:mysql-connector-j'

    // AWS SDK (SES + SNS)
    implementation 'software.amazon.awssdk:ses:2.25.54'
    implementation 'software.amazon.awssdk:sns:2.25.54'
      implementation 'software.amazon.awssdk:apache-client:2.25.0'
    implementation 'software.amazon.awssdk:netty-nio-client:2.25.0'

    // SQS Listener (awspring cloud)
    implementation 'io.awspring.cloud:spring-cloud-aws-starter-sqs:3.1.0'
// Required to override SSL Verification for AWS SDK v2
implementation 'software.amazon.awssdk:url-connection-client:2.25.54'
implementation 'org.apache.httpcomponents.client5:httpclient5:5.3.1'
    implementation 'io.github.cdimascio:dotenv-java:2.2.4'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.6.0'
    
}

tasks.named('test') {
    useJUnitPlatform()
}
