spring.application.name=notification-service

server.port=8086

spring.profiles.active=dev


# =======================
# DATABASE CONFIG
# =======================
spring.datasource.url=jdbc:mysql: //localhost:3306/notification_service
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# =======================
# JPA / HIBERNATE
# =======================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =======================
# LOGGING
# =======================
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.com.example.notificationservice=DEBUG

# =======================
# AWS CONFIG
# =======================

spring.cloud.aws.sqs.enabled=true
spring.cloud.aws.region.auto=false

# AWS
spring.cloud.aws.region.static=
spring.cloud.aws.credentials.access-key=
spring.cloud.aws.credentials.secret-key=

# SES
aws.ses.from-email=

# SQS
aws.sqs.queues.userRegistered=
aws.sqs.queues.orderPlaced=
aws.sqs.queues.orderShipped=
aws.sqs.queues.paymentCompleted=
aws.sqs.queues.paymentFailed=
