spring.application.name=notification-service

server.port=8086

# =======================
# DATABASE CONFIG
# =======================
spring.datasource.url=jdbc:mysql://localhost:3306/notification_service?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# =======================
# JPA / HIBERNATE
# =======================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =======================
# LOGGING
# =======================
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.com.example.notificationservice=DEBUG

# =======================
# AWS CONFIG
# =======================

spring.cloud.aws.sqs.enabled=true
spring.cloud.aws.region.auto=false

# AWS
spring.cloud.aws.region.static=${AWS_REGION}
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_KEY}

# SES
aws.ses.from-email=${SES_FROM_EMAIL}

# SQS
aws.sqs.queues.userRegistered=${SQS_USER_REGISTERED}
aws.sqs.queues.orderPlaced=${SQS_ORDER_PLACED}
aws.sqs.queues.orderShipped=${SQS_ORDER_SHIPPED}
aws.sqs.queues.paymentCompleted=${SQS_PAYMENT_COMPLETED}
aws.sqs.queues.paymentFailed=${SQS_PAYMENT_FAILED}